(defun read-line-numbers ()
  (let ((line (read-line *standard-input* nil nil)))
    (when line
      (with-input-from-string (s line)
        (loop for x = (read s nil nil)
              while x
              collect x)))))

(defun main ()
  (let* ((first-line (read-line-numbers))
         (n (first first-line))
         (m (second first-line))
         (adj (make-array n :initial-element nil)))
    (dotimes (i m)
      (let* ((line (read-line-numbers))
             (u (first line))
             (v (second line))
             (w (third line)))
        (push (cons v w) (aref adj u))
        (push (cons u w) (aref adj v))))
    (let* ((last-line (read-line-numbers))
           (s (first last-line))
           (tt (second last-line)))
      (if (= s tt)
          (format t "0~%")
          (let ((dist (make-array n :initial-element nil))
                (visited (make-array n :initial-element nil)))
            (setf (aref dist s) 0)
            (loop
              (let ((u nil)
                    (best nil))
                (dotimes (i n)
                  (when (and (not (aref visited i))
                             (aref dist i)
                             (or (null best) (< (aref dist i) best)))
                    (setf u i)
                    (setf best (aref dist i))))
                (when (null u) (return))
                (when (= u tt) (return))
                (setf (aref visited u) t)
                (dolist (edge (aref adj u))
                  (let ((v (car edge))
                        (w (cdr edge)))
                    (when (not (aref visited v))
                      (let ((nd (+ (aref dist u) w)))
                        (when (or (null (aref dist v)) (< nd (aref dist v)))
                          (setf (aref dist v) nd))))))))
            (if (aref dist tt)
                (format t "~a~%" (aref dist tt))
                (format t "-1~%")))))))

(main)
