(defun read-line-safe ()
  (or (read-line *standard-input* nil nil) ""))

(defun lcs-length (a b)
  (let* ((n (length a))
         (m (length b))
         (prev (make-array (1+ m) :initial-element 0))
         (curr (make-array (1+ m) :initial-element 0)))
    (dotimes (i n)
      (dotimes (j m)
        (if (char= (char a i) (char b j))
            (setf (aref curr (1+ j)) (1+ (aref prev j)))
            (setf (aref curr (1+ j)) (max (aref prev (1+ j)) (aref curr j)))))
      (rotatef prev curr))
    (aref prev m)))

(let ((a (read-line-safe))
      (b (read-line-safe)))
  (format t "~a~%" (lcs-length a b)))
