(let ((groups (make-hash-table :test 'equal))
      (result '()))
  (loop for line = (read-line *standard-input* nil nil)
        while line
        do (let ((w (string-trim '(#\Space #\Tab #\Return #\Newline) line)))
             (when (> (length w) 0)
               (push w (gethash (sort (copy-seq w) #'char<) groups)))))
  (maphash (lambda (k v)
             (declare (ignore k))
             (push (sort v #'string<) result))
           groups)
  (setf result (sort result #'string< :key #'first))
  (dolist (g result)
    (format t "~{~A~^ ~}~%" g)))
