(declaim (optimize (speed 2) (safety 1)))

(defvar *buf* (make-string 65536))
(defvar *len* 0)
(defvar *pos* 0)

(defun next-char ()
  (when (>= *pos* *len*)
    (setf *len* (read-sequence *buf* *standard-input*) *pos* 0))
  (if (zerop *len*)
      nil
      (prog1 (char *buf* *pos*) (incf *pos*))))

(defun read-int ()
  (let ((c (next-char)) (neg nil) (n 0))
    (loop while (and c (not (or (digit-char-p c) (char= c #\-))))
          do (setf c (next-char)))
    (unless c (return-from read-int nil))
    (when (char= c #\-) (setf neg t c (next-char)))
    (loop while (and c (digit-char-p c))
          do (setf n (+ (* n 10) (digit-char-p c)) c (next-char)))
    (if neg (- n) n)))

(defun main ()
  (let* ((n (read-int)) (m (read-int))
         (adj (make-array n :initial-element nil)))
    (dotimes (i m)
      (let ((u (read-int)) (v (read-int)) (w (read-int)))
        (push (cons v w) (aref adj u))
        (push (cons u w) (aref adj v))))
    (let ((s (read-int)) (tt (read-int)))
      (when (= s tt)
        (format t "0~%")
        (return-from main))
      (let ((dist (make-array n :initial-element nil))
            (heap (make-array 16 :adjustable t :fill-pointer 0)))
        (labels ((hless (i j) (< (car (aref heap i)) (car (aref heap j))))
                 (swap (i j) (rotatef (aref heap i) (aref heap j)))
                 (hpush (d node)
                   (vector-push-extend (cons d node) heap)
                   (let ((i (1- (fill-pointer heap))))
                     (loop while (> i 0)
                           do (let ((p (floor (1- i) 2)))
                                (if (hless i p)
                                    (progn (swap i p) (setf i p))
                                    (return))))))
                 (hpop ()
                   (let ((top (aref heap 0))
                         (last (vector-pop heap)))
                     (when (> (fill-pointer heap) 0)
                       (setf (aref heap 0) last)
                       (let ((i 0) (sz (fill-pointer heap)))
                         (loop
                           (let* ((l (+ (* 2 i) 1)) (r (+ l 1)) (best i))
                             (when (and (< l sz) (hless l best)) (setf best l))
                             (when (and (< r sz) (hless r best)) (setf best r))
                             (if (= best i)
                                 (return)
                                 (progn (swap i best) (setf i best)))))))
                     top)))
          (setf (aref dist s) 0)
          (hpush 0 s)
          (loop while (> (fill-pointer heap) 0)
                do (let* ((e (hpop)) (d (car e)) (u (cdr e)))
                     (when (= u tt)
                       (format t "~D~%" d)
                       (return-from main))
                     (when (= d (aref dist u))
                       (dolist (edge (aref adj u))
                         (let ((v (car edge)) (nd (+ d (cdr edge))))
                           (when (or (null (aref dist v)) (< nd (aref dist v)))
                             (setf (aref dist v) nd)
                             (hpush nd v)))))))
          (format t "-1~%"))))))

(main)
