(defun clean (s)
  (if s
      (remove-if-not #'alpha-char-p s)
      ""))

(let* ((a (clean (read-line *standard-input* nil nil)))
       (b (clean (read-line *standard-input* nil nil)))
       (n (length a))
       (m (length b))
       (prev (make-array (1+ m) :element-type 'fixnum :initial-element 0))
       (cur (make-array (1+ m) :element-type 'fixnum :initial-element 0)))
  (dotimes (i n)
    (let ((ca (char a i)))
      (setf (aref cur 0) 0)
      (dotimes (j m)
        (setf (aref cur (1+ j))
              (if (char= ca (char b j))
                  (1+ (aref prev j))
                  (max (aref prev (1+ j)) (aref cur j))))))
    (rotatef prev cur))
  (format t "~D~%" (aref prev m)))
