(let* ((r (read *standard-input* nil 0))
       (c (read *standard-input* nil 0))
       (m (make-array (list r c))))
  (dotimes (i r)
    (dotimes (j c)
      (setf (aref m i j) (read *standard-input* nil 0))))
  (let ((out (make-string-output-stream)))
    (dotimes (j c)
      (dotimes (i r)
        (when (> i 0) (write-char #\Space out))
        (format out "~D" (aref m i j)))
      (write-char #\Newline out))
    (write-string (get-output-stream-string out))))
