(let ((in (sb-sys:make-fd-stream 0 :input t :external-format :latin-1 :buffering :full))
      (counts (make-hash-table :test #'equal))
      (buf (make-array 16 :element-type 'character :adjustable t :fill-pointer 0)))
  (flet ((flush ()
           (when (> (length buf) 0)
             (incf (gethash (copy-seq buf) counts 0))
             (setf (fill-pointer buf) 0))))
    (loop for c = (read-char in nil nil)
          while c
          do (let ((code (char-code c)))
               (cond ((<= 65 code 90) (vector-push-extend (code-char (+ code 32)) buf))
                     ((<= 97 code 122) (vector-push-extend c buf))
                     (t (flush)))))
    (flush))
  (let ((items '()))
    (maphash (lambda (k v) (push (cons k v) items)) counts)
    (setf items (sort items (lambda (a b)
                              (or (> (cdr a) (cdr b))
                                  (and (= (cdr a) (cdr b))
                                       (string< (car a) (car b)))))))
    (let ((out (make-string-output-stream)))
      (dolist (it items)
        (write-string (car it) out)
        (write-char #\Space out)
        (format out "~D~%" (cdr it)))
      (write-string (get-output-stream-string out) *standard-output*)
      (finish-output *standard-output*))))
