(use-modules (ice-9 rdelim))

;; ---------- input ----------
(define (read-int)
  (let skip ((c (peek-char)))
    (cond ((eof-object? c) c)
          ((char-whitespace? c) (read-char) (skip (peek-char)))
          (else
           (let ((neg (if (char=? c #\-) (begin (read-char) #t) #f)))
             (let loop ((acc 0) (any #f))
               (let ((d (peek-char)))
                 (if (and (not (eof-object? d)) (char-numeric? d))
                     (begin (read-char)
                            (loop (+ (* acc 10) (- (char->integer d) 48)) #t))
                     (if any (if neg (- acc) acc) (read-int))))))))))

;; ---------- binary heap of (dist . node) ----------
(define (make-heap) (vector (make-vector 16 #f) 0))
(define (heap-size h) (vector-ref h 1))
(define (heap-empty? h) (= (heap-size h) 0))

(define (heap-push! h key val)
  (let* ((arr (vector-ref h 0))
         (n (vector-ref h 1)))
    (when (= n (vector-length arr))
      (let ((new (make-vector (* 2 (vector-length arr)) #f)))
        (vector-move-left! arr 0 n new 0)
        (vector-set! h 0 new)
        (set! arr new)))
    (vector-set! h 1 (+ n 1))
    (let up ((i n))
      (if (> i 0)
          (let* ((p (quotient (- i 1) 2))
                 (pe (vector-ref arr p)))
            (if (< key (car pe))
                (begin (vector-set! arr i pe) (up p))
                (vector-set! arr i (cons key val))))
          (vector-set! arr i (cons key val))))))

(define (heap-pop! h)
  (let* ((arr (vector-ref h 0))
         (n (- (vector-ref h 1) 1))
         (top (vector-ref arr 0))
         (last (vector-ref arr n)))
    (vector-set! h 1 n)
    (vector-set! arr n #f)
    (when (> n 0)
      (let down ((i 0))
        (let ((l (+ (* 2 i) 1)) (r (+ (* 2 i) 2)))
          (if (>= l n)
              (vector-set! arr i last)
              (let ((c (if (and (< r n) (< (car (vector-ref arr r)) (car (vector-ref arr l)))) r l)))
                (if (< (car (vector-ref arr c)) (car last))
                    (begin (vector-set! arr i (vector-ref arr c)) (down c))
                    (vector-set! arr i last)))))))
    top))

;; ---------- main ----------
(define (main)
  (let* ((n (read-int)) (m (read-int)))
    (if (eof-object? n)
        #t
        (let ((adj (make-vector n '())))
          (do ((i 0 (+ i 1))) ((= i m))
            (let* ((u (read-int)) (v (read-int)) (w (read-int)))
              (vector-set! adj u (cons (cons v w) (vector-ref adj u)))
              (vector-set! adj v (cons (cons u w) (vector-ref adj v)))))
          (let* ((s (read-int)) (t (read-int))
                 (dist (make-vector n #f))
                 (heap (make-heap)))
            (vector-set! dist s 0)
            (heap-push! heap 0 s)
            (let loop ()
              (if (heap-empty? heap)
                  (display -1)
                  (let* ((e (heap-pop! heap)) (d (car e)) (u (cdr e)))
                    (cond ((= u t) (display d))
                          ((> d (vector-ref dist u)) (loop))
                          (else
                           (for-each
                            (lambda (edge)
                              (let* ((v (car edge)) (nd (+ d (cdr edge)))
                                     (cur (vector-ref dist v)))
                                (when (or (not cur) (< nd cur))
                                  (vector-set! dist v nd)
                                  (heap-push! heap nd v))))
                            (vector-ref adj u))
                           (loop))))))
            (newline))))))

(main)
