(define (main)
  (let ((n (read)))
    (if (or (eof-object? n) (not (integer? n)) (< n 2))
        (newline)
        (let ((sieve (make-vector (+ n 1) #t)))
          (vector-set! sieve 0 #f)
          (vector-set! sieve 1 #f)
          (let loop ((i 2))
            (when (<= (* i i) n)
              (when (vector-ref sieve i)
                (let mark ((j (* i i)))
                  (when (<= j n)
                    (vector-set! sieve j #f)
                    (mark (+ j i)))))
              (loop (+ i 1))))
          (let out ((i 2) (first #t))
            (if (> i n)
                (newline)
                (begin
                  (when (vector-ref sieve i)
                    (if (not first) (display " "))
                    (display i))
                  (out (+ i 1) (and first (not (vector-ref sieve i)))))))))))

(main)
