(define (read-all-ints)
  (let loop ((acc '()))
    (let ((x (read)))
      (if (eof-object? x)
          (reverse acc)
          (loop (cons x acc))))))

(define (main)
  (let* ((ints (read-all-ints))
         (r (car ints))
         (c (cadr ints))
         (data (cddr ints))
         (vec (list->vector data)))
    (do ((j 0 (+ j 1))) ((>= j c))
      (do ((i 0 (+ i 1))) ((>= i r))
        (if (> i 0) (display " "))
        (display (vector-ref vec (+ (* i c) j))))
      (newline))))

(main)
