(define (main)
  (let* ((n (read))
         (m (read))
         (adj (make-vector n '())))
    (let loop ((i 0))
      (when (< i m)
        (let* ((u (read))
               (v (read))
               (w (read)))
          (vector-set! adj u (cons (cons v w) (vector-ref adj u)))
          (vector-set! adj v (cons (cons u w) (vector-ref adj v)))
          (loop (+ i 1)))))
    (let* ((s (read))
           (t (read))
           (inf 1000000000)
           (dist (make-vector n inf))
           (visited (make-vector n #f)))
      (vector-set! dist s 0)
      (let loop ((count 0))
        (when (< count n)
          ;; find unvisited node with minimum dist
          (let find-min ((i 0) (best -1) (best-dist inf))
            (cond
              ((= i n)
               (when (>= best 0)
                 (vector-set! visited best #t)
                 (for-each
                  (lambda (edge)
                    (let* ((v (car edge))
                           (w (cdr edge))
                           (nd (+ (vector-ref dist best) w)))
                      (when (and (not (vector-ref visited v))
                                 (< nd (vector-ref dist v)))
                        (vector-set! dist v nd))))
                  (vector-ref adj best))))
              ((and (not (vector-ref visited i)) (< (vector-ref dist i) best-dist))
               (find-min (+ i 1) i (vector-ref dist i)))
              (else
               (find-min (+ i 1) best best-dist))))
          (loop (+ count 1))))
      (let ((d (vector-ref dist t)))
        (if (>= d inf)
            (display -1)
            (display d))
        (newline)))))

(main)
