(define (read-ints)
  (let loop ((acc '()))
    (let ((n (read)))
      (if (eof-object? n)
          (reverse acc)
          (loop (cons n acc))))))

(define (main)
  (let* ((r (read))
         (c (read))
         (rows (let loop ((i 0) (acc '()))
                 (if (= i r)
                     (reverse acc)
                     (let ((row (let iloop ((j 0) (racc '()))
                                  (if (= j c)
                                      (reverse racc)
                                      (iloop (+ j 1) (cons (read) racc))))))
                       (loop (+ i 1) (cons row acc)))))))
    (let ((vecs (map list->vector rows)))
      (let loop ((j 0))
        (when (< j c)
          (let loop2 ((i 0))
            (when (< i r)
              (display (vector-ref (list-ref vecs i) j))
              (when (< (+ i 1) r) (display " "))
              (loop2 (+ i 1))))
          (newline)
          (loop (+ j 1)))))))

(main)
