(use-modules (ice-9 rdelim))

(define (string-split-spaces str)
  (let loop ((i 0)
             (start 0)
             (result '()))
    (if (>= i (string-length str))
        (if (> i start)
            (reverse (cons (substring str start i) result))
            (reverse result))
        (if (char=? (string-ref str i) #\space)
            (if (> i start)
                (loop (+ i 1) (+ i 1) (cons (substring str start i) result))
                (loop (+ i 1) start result))
            (loop (+ i 1) start result)))))

(define (read-line-numbers)
  (let ((line (read-line)))
    (if (eof-object? line)
        '()
        (map string->number (string-split-spaces line)))))

(define (read-matrix r)
  (if (= r 0)
      '()
      (cons (read-line-numbers)
            (read-matrix (- r 1)))))

(define (transpose matrix)
  (if (null? matrix)
      '()
      (if (null? (car matrix))
          '()
          (cons (map car matrix)
                (transpose (map cdr matrix))))))

(define (numbers->string numbers)
  (let loop ((nums numbers)
             (result ""))
    (if (null? nums)
        result
        (if (string=? result "")
            (loop (cdr nums) (number->string (car nums)))
            (loop (cdr nums) (string-append result " " (number->string (car nums))))))))

(define (print-matrix matrix)
  (if (not (null? matrix))
      (begin
        (display (numbers->string (car matrix)))
        (newline)
        (print-matrix (cdr matrix)))))

(let* ((rc (read-line-numbers))
       (r (car rc))
       (c (cadr rc))
       (matrix (read-matrix r)))
  (print-matrix (transpose matrix)))
