(define r (read))
(define c (read))
(define m (make-vector (* r c) 0))
(do ((i 0 (+ i 1))) ((= i (* r c)))
  (vector-set! m i (read)))
(do ((j 0 (+ j 1))) ((= j c))
  (do ((i 0 (+ i 1))) ((= i r))
    (if (> i 0) (display " "))
    (display (vector-ref m (+ (* i c) j))))
  (newline))
