(defun trim-line (line)
  (string-right-trim '(#\Return #\Newline #\Space #\Tab) line))

(defun main ()
  (let ((table (make-hash-table :test 'equal))
        (words '()))
    (loop for raw = (read-line *standard-input* nil nil)
          while raw
          do (let ((w (trim-line raw)))
               (when (plusp (length w))
                 (push w words))))
    (dolist (w (nreverse words))
      (let ((key (sort (copy-seq w) #'char<)))
        (push w (gethash key table))))
    (let ((groups '()))
      (maphash (lambda (k v)
                 (declare (ignore k))
                 (push (sort v #'string<) groups))
               table)
      (setf groups (sort groups #'string< :key #'first))
      (dolist (g groups)
        (format t "~{~A~^ ~}~%" g)))))

(main)
