;;; Shortest path via Dijkstra with a binary min-heap.

(defun read-int (stream)
  "Read one non-negative/negative integer from STREAM, skipping whitespace. Returns NIL at EOF."
  (let ((c (peek-char t stream nil nil)))
    (when (null c) (return-from read-int nil))
    (let ((neg nil) (val 0) (any nil))
      (when (char= c #\-)
        (setf neg t)
        (read-char stream))
      (loop for ch = (peek-char nil stream nil nil)
            while (and ch (digit-char-p ch))
            do (setf val (+ (* val 10) (digit-char-p ch))
                     any t)
               (read-char stream))
      (if any (if neg (- val) val) nil))))

;;; Binary heap of (dist . node) pairs keyed on dist.
(defstruct heap
  (data (make-array 16 :adjustable t :fill-pointer 0)))

(defun heap-push (h dist node)
  (let ((a (heap-data h)))
    (vector-push-extend (cons dist node) a)
    (let ((i (1- (fill-pointer a))))
      (loop while (> i 0)
            do (let ((p (floor (1- i) 2)))
                 (if (< (car (aref a i)) (car (aref a p)))
                     (progn (rotatef (aref a i) (aref a p))
                            (setf i p))
                     (return)))))))

(defun heap-pop (h)
  (let* ((a (heap-data h))
         (top (aref a 0))
         (last (vector-pop a))
         (n (fill-pointer a)))
    (when (> n 0)
      (setf (aref a 0) last)
      (let ((i 0))
        (loop
          (let ((l (+ (* 2 i) 1))
                (r (+ (* 2 i) 2))
                (m i))
            (when (and (< l n) (< (car (aref a l)) (car (aref a m))))
              (setf m l))
            (when (and (< r n) (< (car (aref a r)) (car (aref a m))))
              (setf m r))
            (if (= m i)
                (return)
                (progn (rotatef (aref a i) (aref a m))
                       (setf i m)))))))
    top))

(defun heap-empty-p (h)
  (zerop (fill-pointer (heap-data h))))

(defun main ()
  (let* ((in *standard-input*)
         (n (read-int in))
         (m (read-int in)))
    (when (null n) (return-from main))
    (let ((adj (make-array n :initial-element nil)))
      (dotimes (i m)
        (let ((u (read-int in))
              (v (read-int in))
              (w (read-int in)))
          (push (cons v w) (aref adj u))
          (push (cons u w) (aref adj v))))
      (let ((s (read-int in))
            (tt (read-int in)))
        (if (= s tt)
            (format t "0~%")
            (let ((dist (make-array n :initial-element nil))
                  (heap (make-heap)))
              (setf (aref dist s) 0)
              (heap-push heap 0 s)
              (loop until (heap-empty-p heap)
                    do (let* ((top (heap-pop heap))
                              (d (car top))
                              (u (cdr top)))
                         (when (= d (aref dist u))
                           (when (= u tt) (return))
                           (dolist (e (aref adj u))
                             (let ((v (car e))
                                   (nd (+ d (cdr e))))
                               (when (or (null (aref dist v))
                                         (< nd (aref dist v)))
                                 (setf (aref dist v) nd)
                                 (heap-push heap nd v)))))))
              (let ((ans (aref dist tt)))
                (format t "~A~%" (if ans ans -1)))))))))

(main)
