(defun strip-cr (s)
  (string-right-trim '(#\Return #\Newline) s))

(defun lcs-length (a b)
  (declare (type simple-string a b))
  (let* ((n (length a))
         (m (length b))
         (prev (make-array (1+ m) :element-type 'fixnum :initial-element 0))
         (cur (make-array (1+ m) :element-type 'fixnum :initial-element 0)))
    (declare (type (simple-array fixnum (*)) prev cur))
    (dotimes (i n)
      (let ((ca (char a i)))
        (setf (aref cur 0) 0)
        (dotimes (j m)
          (setf (aref cur (1+ j))
                (if (char= ca (char b j))
                    (1+ (aref prev j))
                    (max (aref prev (1+ j)) (aref cur j))))))
      (rotatef prev cur))
    (aref prev m)))

(let* ((a (or (read-line *standard-input* nil) ""))
       (b (or (read-line *standard-input* nil) "")))
  (format t "~D~%" (lcs-length (coerce (strip-cr a) 'simple-string)
                               (coerce (strip-cr b) 'simple-string))))
