(defun rle (s)
  (with-output-to-string (out)
    (let ((n (length s))
          (i 0))
      (loop while (< i n)
            do (let ((c (char s i))
                     (j i))
                 (loop while (and (< j n) (char= (char s j) c))
                       do (incf j))
                 (write-char c out)
                 (format out "~D" (- j i))
                 (setf i j))))))

(defun main ()
  (let* ((line (or (read-line *standard-input* nil "") ""))
         (trimmed (string-right-trim '(#\Return #\Newline #\Space #\Tab) line)))
    (write-string (rle trimmed))
    (terpri)))

(main)
